### ISSUE TITLE
[Crash]: Exit Code: 0 [NOT UNIVERSITY, FTB APP BUG, TRY USING MULTIMC]

### ISSUE THREAD

**Issue by jiru6552** [FTBTeam/FTB-University#17]
* What version of University: 1.0.0
* Have you added any mods: No
* If yes, which mods:
* Crash report link (preferably Pastebin etc, not the file): 
[latest.log](https://github.com/FTBTeam/FTB-University/files/5397956/latest.log)

* What were you doing when the crash happened: 1) I downloaded the FTB launcher. 2) I downloaded FTB University. 3) I launched FTB university. 4) Pressed start. 5) Exit Code: 0. 
* Any other details:
I've tried allocating more memory to the pack (~8GB) same results. I've updated my java, same results. I even tried to download the forge version its running on and replaced it, same results.

**Comment by aaronhowser1** [comment]
```java
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:169) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:114) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:77) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:164) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 2 more
```
Very strange. Try deleting the modpack (and clearing the launcher cache) and trying again.

**Comment by jiru6552** [comment]
I did as you said, I still got exit code: 0, I then tried deleting and reinstalling the FTB launcher, same issue, and the I did what you said one more time, same problem.
[latest.log](https://github.com/FTBTeam/FTB-University/files/5397979/latest.log)
Just checking though, when you said to clear the launcher cache, did you mean to press "refresh cache" in the FTB launcher's settings page at the bottom (what I did), or is there something else I'm supposed to do.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/96378112-997b1100-114f-11eb-80cf-309859d0048b.png)

**Comment by jiru6552** [comment]
I tested a few other packs on the launcher. I'm getting this problem only for all the 1.12.2 packs.

**Comment by jiru6552** [comment]
I'm able to run 1.12.2 mods on other launchers (twitch and technic) so I'm not sure why this is specific to the FTB launcher

**Comment by jiru6552** [comment]
Ok, I got it to work...Kinda. What I did is I used the Twitch launcher, created a new custom profile set to forge 14.23.5.2847 for 1.12.2. I then open the folder it created, deleted everything inside, then dumped the contents of the FTB University instance folder from the FTB launcher into it. I then Just launched FTB University from the Twitch launcher. So what I'm getting from this is that there is something with the FTB launcher and/or my computer in which 1.12.2 packs from the launcher will not cooperate with me.
