### ISSUE TITLE
Nature's compass causing soft crash

### ISSUE THREAD

**Issue by Prolixitas** [FTBTeam/FTB-University#19]
I attempted to use nature's compass to find a mountain biome after selecting it from the list, and the compass showed that no mountain biome was found. When I try to right click to open the biome selection menu I get a crash and sent back to the main menu. I shift right clicked the compass which appeared to clear the selection and tried to open the selection menu again with the same result. I also attempted to get a new compass and the crash still occurred when trying to open the selection menu. This is what is found at the beginning of the crashlog. 

Time: 2020-10-18 17:09:23 EDT
Description: Rendering screen

java.lang.NullPointerException
    at com.chaosthedude.naturescompass.gui.GuiListBiomesEntry.drawEntry(GuiListBiomesEntry.java:34)
    at net.minecraft.client.gui.GuiListExtended.drawSlot(SourceFile:25)
    at com.chaosthedude.naturescompass.gui.GuiListBiomes.drawSelectionBox(GuiListBiomes.java:111)
    at com.chaosthedude.naturescompass.gui.GuiListBiomes.drawScreen(GuiListBiomes.java:85)
    at com.chaosthedude.naturescompass.gui.GuiNaturesCompass.drawScreen(GuiNaturesCompass.java:104)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by aaronhowser1** [comment]
We need the __entire__ crash report. Upload the file to pastebin or something and link it here.

**Comment by Prolixitas** [comment]
Here is a link to the paste of the log. https://pastebin.com/5t5nWutX

I restarted my game and was able to open the biome selection screen again, but trying a second time even with no selection and any time after the crash without resetting is still causing the crash.

**Comment by natebc** [comment]
Same with me, here's a gist of my crash log:
https://gist.github.com/natebc/1e4c14acf2dd943b105a419b505d02e6
