### ISSUE TITLE
Game crashes when trying to open Quest[Quest Problem]: 

### ISSUE THREAD

**Issue by Nico343434** [FTBTeam/FTB-University#200]
* What version of University:1.1.1
* What quest:Mekanism Line
* What is the problem:When I try to open the Mekanism quest line under technology and it freezes my game for about 5 minutes and after that i have black bars around my screen.

**Comment by aaronhowser1** [comment]
Can you post your latest.log? I've never seen this.

**Comment by Nico343434** [comment]
[latest.log](https://github.com/FTBTeam/FTB-University/files/5541504/latest.log)

this is the latest i dont think its of any use cause the game never fully crashed I will try it again and send a screenshot

**Comment by aaronhowser1** [comment]
```
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1486) ~[buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.BufferBuilder.begin(BufferBuilder.java:303) ~[buk.class:?]
	at com.feed_the_beast.ftblib.lib.gui.GuiHelper.drawTexturedRect(GuiHelper.java:114) ~[GuiHelper.class:?]
	at com.feed_the_beast.ftblib.lib.icon.ImageIcon.draw(ImageIcon.java:93) ~[ImageIcon.class:?]
	at com.feed_the_beast.ftbquests.gui.tree.ButtonQuest.draw(ButtonQuest.java:465) ~[ButtonQuest.class:?]
	at com.feed_the_beast.ftblib.lib.gui.Panel.drawWidget(Panel.java:282) ~[Panel.class:?]
	at com.feed_the_beast.ftblib.lib.gui.Panel.draw(Panel.java:253) ~[Panel.class:?]
	at com.feed_the_beast.ftbquests.gui.tree.PanelQuests.draw(PanelQuests.java:367) ~[PanelQuests.class:?]
	at com.feed_the_beast.ftblib.lib.gui.Panel.drawWidget(Panel.java:282) ~[Panel.class:?]
	at com.feed_the_beast.ftblib.lib.gui.Panel.draw(Panel.java:253) ~[Panel.class:?]
	at com.feed_the_beast.ftblib.lib.gui.GuiBase.draw(GuiBase.java:273) ~[GuiBase.class:?]
	at com.feed_the_beast.ftblib.lib.gui.GuiWrapper.drawScreen(GuiWrapper.java:137) ~[GuiWrapper.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660) ~[Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456) ~[buq.class:?]
	... 9 more
[22:37:01] [Client thread/FATAL] [VanillaFix]: Minecraft ran into a problem! Report saved to: C:\Users\nico2\.ftba\instances\ef437352-16af-4e19-80b3-e845a2d568c6\crash-reports\crash-2020-11-14_22.37.01-client.txt
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2020-11-14 22:37:01 CET
Description: Rendering screen

java.lang.IllegalStateException: Already building!
    at net.minecraft.client.renderer.BufferBuilder.begin(BufferBuilder.java:303)
    at com.feed_the_beast.ftblib.lib.gui.GuiHelper.drawTexturedRect(GuiHelper.java:114)
    at com.feed_the_beast.ftblib.lib.icon.ImageIcon.draw(ImageIcon.java:93)
    at com.feed_the_beast.ftbquests.gui.tree.ButtonQuest.draw(ButtonQuest.java:465)
    at com.feed_the_beast.ftblib.lib.gui.Panel.drawWidget(Panel.java:282)
    at com.feed_the_beast.ftblib.lib.gui.Panel.draw(Panel.java:253)
    at com.feed_the_beast.ftbquests.gui.tree.PanelQuests.draw(PanelQuests.java:367)
    at com.feed_the_beast.ftblib.lib.gui.Panel.drawWidget(Panel.java:282)
    at com.feed_the_beast.ftblib.lib.gui.Panel.draw(Panel.java:253)
    at com.feed_the_beast.ftblib.lib.gui.GuiBase.draw(GuiBase.java:273)
    at com.feed_the_beast.ftblib.lib.gui.GuiWrapper.drawScreen(GuiWrapper.java:137)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```
Can you post that crash report, and I can forward to the mod author?

**Comment by Nico343434** [comment]
I can't seem to find the crash... So good news is, that it's working now even though in the last session I changed nothing in the settings nor did I add any mod... but still thanks for the fast reply and sorry for wasting your time.

**Comment by aaronhowser1** [comment]
No problem. Strange that it would say it made a crash report, without actually making one though. If it happens again, I'll reopen.
