### ISSUE TITLE
[Crash]: Game keeps crashing again and again

### ISSUE THREAD

**Issue by Jinxy2004** [FTBTeam/FTB-University#228]
What version of University: 1.1.1
 Have you added any mods: No.
Crash report link (preferably Pastebin etc, not the file): https://pastebin.com/xcnjn6a5
What were you doing when the crash happened: Placing down my tier 6 solar cells in a RF tools time dimension. 
 Any other details: This has been happening quite a bit and sometimes I'm unable to get into the world, other times it just keeps loading me in and crashes again.

**Comment by aaronhowser1** [comment]
```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at com.latmod.yabba.tile.TileItemBarrelConnector.insertItem(TileItemBarrelConnector.java:202)
    at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:45)
    at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:135)
    at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:93)
    at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:139)
    at org.cyclops.cyclopscore.ingredient.storage.IngredientStorageHelpers.insertIngredientQuantity(IngredientStorageHelpers.java:763)
    at org.cyclops.cyclopscore.ingredient.storage.IngredientStorageHelpers.insertIngredient(IngredientStorageHelpers.java:787)
    at org.cyclops.cyclopscore.ingredient.storage.IngredientStorageHelpers.moveIngredientsSlotted(IngredientStorageHelpers.java:401)
    at org.cyclops.cyclopscore.ingredient.storage.IngredientStorageHelpers.moveIngredientsSlotted(IngredientStorageHelpers.java:314)
    at org.cyclops.integratedtunnels.core.TunnelHelpers.moveSingle(TunnelHelpers.java:61)
    at org.cyclops.integratedtunnels.core.TunnelHelpers.moveSingleStateOptimized(TunnelHelpers.java:133)
```
Looks like it's either Common Capabilities or Integrated Dynamics at fault here. Can you try making a backup of the world, and removing ID (and its addons) and seeing if it works? I'll forward this to the CC issue tracker.

**Comment by aaronhowser1** [comment]
Or YABBA maybe? Try removing that one first.
