### ISSUE TITLE
Player being kicked from LAN connection

### ISSUE THREAD

**Issue by Monkalo** [FTBTeam/FTB-University#269]
This problem occurs when the second player joins the world after it is opened to LAN. The player exists on the server for anywhere between 1 to 20 seconds before being kicked. Subsequent attempts have the same results with a java.lang.NullPointerException error. This only started recently, within the last few days, and before this the world was working perfectly over LAN.

I tried deleting the playerdata files for the second player and this resulted a full twenty minutes of game play before the player was kicked and the issue repeated itself.

Here is the relevant bit from the crash log:

Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.minecraft.network.play.server.SPacketEntityHeadLook.getEntity(SourceFile:42)
    at net.minecraft.client.network.NetHandlerPlayClient.handleEntityHeadLook(NetHandlerPlayClient.java:644)
    at net.minecraft.network.play.server.SPacketEntityHeadLook.processPacket(SourceFile:38)
    at net.minecraft.network.play.server.SPacketEntityHeadLook.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

Thank you for your time!

**Comment by aaronhowser1** [comment]
I would need the entire crash report, preferably a link to pastebin or something similar.

LAN tends to be buggy in general, though.

**Comment by Monkalo** [comment]
Of course, I'll link that tonight. Thanks for looking.

**Comment by Monkalo** [comment]
Here is the link to the log I paraphrased above.
https://pastebin.com/rb8DJaSR

This is the most recent crash log.
https://pastebin.com/3qadZ4Hw

Thank you!
